language: python
python: 3.5
install:
  - pip install tox
  - pip install coverage
script:
  - tox
env:
  - TOXENV=py27-django18
  - TOXENV=py34-django18
  - TOXENV=py35-django18
branches:
  only:
    - stable/2.8.x
